version: 2
defaults: &defaults
  working_directory: /go/src/github.com/pilosa/go-pilosa
  docker:
    - image: circleci/golang:1.10
fast-checkout: &fast-checkout
  attach_workspace:
    at: .
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - vendor-cache-{{ checksum "Gopkg.lock" }}
      - run: "[ -d vendor ] || make vendor"
      - save_cache:
          key: vendor-cache-{{ checksum "Gopkg.lock" }}
          paths:
            - vendor
      - persist_to_workspace:
          root: .
          paths: "*"
  linter:
    <<: *defaults
    steps:
      - *fast-checkout
      - run: go get -u github.com/alecthomas/gometalinter
      - run: gometalinter --install
      - run: go get github.com/remyoudompheng/go-misc/deadcode
      - run: make gometalinter
  test-golang-1.10: &base-test
    <<: *defaults
    steps:
      - *fast-checkout
      - run: mkdir build
      - run: make build/test.pilosa.local.key
      - setup_remote_docker
      - run: |
          docker create -v /tls --name conf alpine:3.4 /bin/true
          docker cp build/test.pilosa.local.* conf:/tls
          docker run --volumes-from conf pilosa/pilosa:v1.1.0 --metric.diagnostics=false -b https://:20101 --tls.skip-verify --tls.certificate /tls/test.pilosa.local.crt --tls.key /tls/test.pilosa.local.key --cluster.disabled static
      - run: |
          docker create -v /go/src/github.com/pilosa/go-pilosa --name go-pilosa alpine:3.4 /bin/true
          docker cp * go-pilosa:/go/src/github.com/pilosa/go-pilosa
          docker run --volumes-from go-pilosa circleci/golang:1.10 -e PILOSA_BIND=https://:20101 --workdir /go/src/github.com/pilosa/go-pilosa make test-all
    docker:
      - image: circleci/golang:1.10
      - image: pilosa/pilosa:v1.1.0
  test-golang-1.9:
    <<: *base-test
    docker:
      - image: circleci/golang:1.9
      - image: pilosa/pilosa:v1.1.0
workflows:
  version: 2
  test:
    jobs:
      - build
      - linter:
          requires:
            - build
      - test-golang-1.10:
          requires:
            - build
      - test-golang-1.9:
          requires:
            - build
